zeebe:
  client:
    broker:
      gatewayAddress: "ZEEBE_GATEWAY_HOST:443"
    security:
      plaintext: false
    cloud:
      client-id: "zeebe"
      client-secret: "ZEEBE_CLIENT_SECRET"
      auth-url: "https://KEYCLOAK_HOST:443/auth/realms/camunda-platform/protocol/openid-connect/token"

tasklist:
  client:
    authorizationUrl: "https://KEYCLOAK_HOST/auth/realms/camunda-platform/protocol/openid-connect/token"
    clientId: "tasklist"
    clientSecret: "TASKLIST_CLIENT_SECRET"
    contentType: "application/x-www-form-urlencoded"
    taskListBaseUrl: "https://TASKLIST_HOST/tasklist"
    audience: "tasklist.camunda.io"
